include:
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/values/.ci-common-api-values.yml'
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/.gitlab-ci/.build-gradle-template.yml'
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/.gitlab-ci/.check-sonarqube-common-api-template.yml'
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/.gitlab-ci/.build-image-template.yml'
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/.gitlab-ci/.deploy-configmap-template.yml'
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/.gitlab-ci/.deploy-secret-template.yml'
  - project: '$MANAGED_PROJECT'
    ref: '$MANAGED_PROJECT_REF'
    file: '/.gitlab-ci/.deploy-helm-template.yml'

stages:
  - build
  - docker
  - pre-deploy
  - deploy
